### ISSUE TITLE
Q: Is it possible to add a MenuItem and always show Text/Label

### ISSUE THREAD

**Issue by waynephipps** [Cheesebaron/LegacyBar#47] opened 2013-06-03 09:24 UTC
With the Android action bar, it's possible to add a menu option and set it to show the text label.

Is this possible with LegacyBar? I can't see how to do it

As a workaround I've been nesting views in the XML which looks messy and partly defeats the objective of using the LegacyBar but perhaps I've missed something?

**Comment by Cheesebaron** [comment] 2013-06-03 11:12
It is not possible at the moment. You are always welcome to fork the project and add it yourself :) However I have been looking at it and it seems to be a messy thing to implement, because `ImageButton` does not support text inside of it, however it might be doable with a normal `Button` setting the topDrawable to the Icon and then setting the text of it.

**Comment by jamesmontemagno** [comment] 2013-06-12 04:19
I have been thinking of changing this up so they are buttons and the text moves to the right of the image. Seems doable.

**Comment by waynephipps** [comment] 2013-06-17 11:37
That would be fantastic. I've been watching this project and hoping for an update. I'd love to contribute but don't have any flexibility given the current workload I'm under.

**Comment by waynephipps** [comment] 2013-06-17 11:40
Sorry, clicked Close & Comment thinking that it would close the view/window of the thread not actually mark the issue as closed. Duh!

**Comment by Cheesebaron** [comment] 2013-07-19 20:42
Duplicate of #26 Closing.

**Closed as completed by Cheesebaron** 2013-07-19 20:42 UTC
Labels: enhancement

**Comment by jamesmontemagno** [comment] 2013-07-20 21:12
I will be implementing this feature this weekend.

**Comment by Cheesebaron** [comment] 2013-07-21 10:23
Just a brain storm. Thinking of just using a `Button` instead of `ImageButton` and set the Left `Drawable` to the Icon of the button and set the text depending on the `ActionType` is set to `WithText` or there is no Icon.
